### PR TITLE
50589 [Bug]: dts-gen should remove @jscrambler tags

### PR DESCRIPTION
**Pull request by rbruckheimer**
Removed tags like @jscrambler, @function, @class
Now able to create proper typescript for module functions.

Task-URL: https://devservices.chartiq.com/kanbanize/50589

### CODE REVIEW

**Comment by jdrichards50** [comment]
@rbruckheimer, I'm getting the below message when running the dts-generator against the latest chartiq.js in master. Looks like a good catch due to your notedObject changed. I'm guessing that **valueFromInterpolation** needs a memberof tag? 
```
 > dts-gen@1.5.2 example:prototypes /Users/jacobrichards/git/dts-generator
> node src/index.js -f examples/chartiq.js -t examples/chartiq.d.ts -c src/config.js

Found unclassified jsdoc: CIQ.ChartEngine.prototype.valueFromInterpolation = function (	bar,	fieldName,	subField,	panel,	yAxis)
File chartiq.d.ts sucessfully created.
```

**Comment by rbruckheimer** [comment]
> @rbruckheimer, I'm getting the below message when running the dts-generator against the latest chartiq.js in master. Looks like a good catch due to your notedObject changed. I'm guessing that **valueFromInterpolation** needs a memberof tag?
> 
> ```
>  > dts-gen@1.5.2 example:prototypes /Users/jacobrichards/git/dts-generator
> > node src/index.js -f examples/chartiq.js -t examples/chartiq.d.ts -c src/config.js
> 
> Found unclassified jsdoc: CIQ.ChartEngine.prototype.valueFromInterpolation = function (	bar,	fieldName,	subField,	panel,	yAxis)
> File chartiq.d.ts sucessfully created.
> ```

Why don't I see this message when I run `npm run build:quick`?

**Comment by rbruckheimer** [comment]
> > @rbruckheimer, I'm getting the below message when running the dts-generator against the latest chartiq.js in master. Looks like a good catch due to your notedObject changed. I'm guessing that **valueFromInterpolation** needs a memberof tag?
> > ```
> >  > dts-gen@1.5.2 example:prototypes /Users/jacobrichards/git/dts-generator
> > > node src/index.js -f examples/chartiq.js -t examples/chartiq.d.ts -c src/config.js
> > 
> > Found unclassified jsdoc: CIQ.ChartEngine.prototype.valueFromInterpolation = function (	bar,	fieldName,	subField,	panel,	yAxis)
> > File chartiq.d.ts sucessfully created.
> > ```
> 
> Why don't I see this message when I run `npm run build:quick`?

Actually, I don't understand what you are running.  There is no chartiq.js in master.

**Comment by jdrichards50** [comment]
> 

I ran dts-generator on chartiq.js that I copied over.

**Comment by jdrichards50** [comment]
> > @rbruckheimer, I'm getting the below message when running the dts-generator against the latest chartiq.js in master. Looks like a good catch due to your notedObject changed. I'm guessing that **valueFromInterpolation** needs a memberof tag?
> > ```
> >  > dts-gen@1.5.2 example:prototypes /Users/jacobrichards/git/dts-generator
> > > node src/index.js -f examples/chartiq.js -t examples/chartiq.d.ts -c src/config.js
> > 
> > Found unclassified jsdoc: CIQ.ChartEngine.prototype.valueFromInterpolation = function (	bar,	fieldName,	subField,	panel,	yAxis)
> > File chartiq.d.ts sucessfully created.
> > ```
> 
> Why don't I see this message when I run `npm run build:quick`?

We will once we check this into production.

**Review by jdrichards50 — APPROVED** [review]
jscrambler, function, and instance tags no longer appear in typescript definitions.

**Pull request merged**
